apiVersion: apps/v1
kind: Deployment
metadata:
  name: deel-assessment
spec:
  selector:
    matchLabels:
      app: deel-assessment
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: deel-assessment
    spec:
      containers:
      - name: deel-assessment
        image: REPOSITORY_TAG
  
---
apiVersion: v1
kind: Service
metadata:
  name: deel-assessment-svc

spec:

  selector:
    app: deel-assessment

  ports:
    - name: http
      port: 80
